### ISSUE TITLE
sp_utf8_encode return value

### ISSUE THREAD

**Issue by cablehead** [imgix/siphon#6]
It looks like `sp_utf8_encode` returns the number of bytes written to the target buffer and not the number of bytes consumed from the source buffer.

https://github.com/imgix/siphon/blob/master/lib/utf8.c#L211
https://github.com/imgix/siphon/blob/master/lib/utf8.c#L516

Which might be OK too.. Just opening up discussion about it.

**Comment by kalamay** [comment]
That's correct. `sp_utf8_encode` takes in a length and encodes all of it or fails. It could return the input length, but I don't suspect that would be too useful. The input length is obviously already known, but the encoded length is not. The `sp_utf8_*_encode` functions are the ones that return the number of bytes consumed, as they are responsible for ensuring proper encoding. Its not possible to know the number of bytes that will be consumed otherwise. The length passed to those functions is the number of bytes in the buffer, and it represents the maximum number of bytes that could be consumed.

The short of it is that these functions return the otherwise unknown piece of information rather than just returning an input parameter. The `sp_utf8_*_encode` functions can't really be changed, but `sp_utf8_encode` is meant more as a convenience function. If there is something that would be more convenient it might be possible to change. This is all true for decode functions as well.

**Comment by cablehead** [comment]
ah gotcha. that makes sense.
